-- Modify "books" table
ALTER TABLE "books" ALTER COLUMN "title" SET NOT NULL, ALTER COLUMN "body" SET NOT NULL, ALTER COLUMN "price" TYPE bigint, ALTER COLUMN "price" SET NOT NULL, ALTER COLUMN "thoughts" SET NOT NULL;
-- Create "posts" table
CREATE TABLE "posts" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "title" character varying NOT NULL,
  "content" character varying NOT NULL,
  "user_posts" bigint NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "posts_users_posts" FOREIGN KEY ("user_posts") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL
);
